M48
; DRILL file KiCad 10.0.6 date 2026-09-01T18:20:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-01T18:20:26-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.020
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X91.794Y-27.26
X106.794Y-27.26
T2
X27.295Y-29.08
X27.295Y-59.42
X113.584Y-29.02
X113.584Y-59.36
M30
