M48
; DRILL file {KiCad 9.0.4} date 2026-01-15T15:25:33-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-15T15:25:33-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X81.17Y-54.25
X81.17Y-64.95
T2
X86.16Y-38.93
X86.16Y-98.92
X126.43Y-38.93
X126.43Y-98.92
M30
