M48
; DRILL file {KiCad 9.0.1} date 2025-04-11T22:39:54-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-11T22:39:54-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.397
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X40.85Y-99.7
X51.8Y-110.6
X83.1Y-99.45
T2
X36.75Y-82.95
X36.75Y-106.5
X79.4Y-82.8
X79.4Y-106.35
M30
