M48
; DRILL file {KiCad 9.0.4} date 2026-02-19T19:42:06-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-19T19:42:06-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.020
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.300
%
G90
G05
T1
X98.7Y-85.5
X119.7Y-85.5
T2
X43.5Y-43.0
X43.5Y-92.0
X159.0Y-42.75
X159.0Y-92.0
M30
